### ISSUE TITLE
Implement notifyListeners method on StateNotifier

### ISSUE THREAD

**Issue by jamiewest** [rrousselGit/state_notifier#10]
I think it would be helpful to have a `notifyListeners` method on the `StateNotifier` class to more closely resemble a `ChangeNotifier`. 

This would go along with using `StateNotifier` in manner similar to `ChangeNotifier`.

```dart
class Person extends StateNotifier<Person> {
   String _email;
   const Person({this.name});
   
   final String name;
   
   String get email => _email;

   set email(String value) {
      _email = value;
      notifyListeners();
      // as opposed to... 
      state = this; // would even this work??
   }
}
```

**Comment by rrousselGit** [comment]
This is not how you should use `StateNotifier`.
You should not have state that needs to be listened, that is not part of the `state` variable.

Instead do:


```dart
class Person {
  String email = '';
  String name = '';
}

class PersonController extends StateNotifier<Person> {
  PersonController(): super(Person());

  set email(String value) {
    state = Person()
      ..email = value
      ..name = state.name;
  }
}
```

**Comment by jamiewest** [comment]
Was this a design choice to have the `State` and `StateNotifier` be to separate components or was due to an engineering requirement in order to make things work with provider?

**Comment by rrousselGit** [comment]
This is a design choice.
StateNotifier is not ChangeNotifier, but ValueNotifier

**Comment by jamiewest** [comment]
I see, that is probably where I am confusing things. Thank you.

**Comment by venkatd** [comment]
Not sure if this is against the intended design, but if you're looking for something like ChangeNotifier but decoupled from Flutter, you can accomplish something like it as so:

```dart
class StateChangeNotifier extends StateNotifier<void> {
  StateChangeNotifier() : super(null);
  void notifyListeners() => state = null;
}
```
