### ISSUE TITLE
ProxyProvider for StateNotifier

### ISSUE THREAD

**Issue by chimon2000** [rrousselGit/state_notifier#16]
I am currently trying to rebuild my StateNotifierProvider based on some external values, but cannot find a way to achieve this.  Basically I have something like the following:

```dart
 IssueQuery(
    organization: state.organization,
    initialCount: 25,
    builder: (state, {fetchMore, refetch}) {
      return MultiProvider(
        providers: [
          StateNotifierProvider(
            create: (context) => QueryController(
              state,
              fetchMore: fetchMore,
              refetch: refetch,
            ),
          ),
        ],
        child: MaterialApp(
          theme: ThemeData(
            primarySwatch: Colors.blueGrey,
          ),
          home: HomePage(),
        ),
      );
    },
  );
```

The state from the builder method should trigger a new state for QueryController but it isn't.

**Comment by smiLLe** [comment]
You could expose the state, fetchMore and refetch on another StateNotifier and use LocatorMixin in QueryController to handle changes on state

**Comment by chimon2000** [comment]
@smiLLe wouldn't that have the same issue of not updating when they are passed into the provider?

**Comment by smiLLe** [comment]
You don't pass them into the constructer but watch their values through the LocatorMixin in your QueryController

**Comment by rrousselGit** [comment]
As stated by smiLLe, use LocatorMixin's update method to _modify_ the StateNotifier instead ore -recreating it.
