### ISSUE TITLE
LocatorMixin not working on Flutter Web release mode

### ISSUE THREAD

**Issue by justinenerio** [rrousselGit/state_notifier#18]
Steps to Reproduce
1. Run the `flutter create .` on example to generate web files
2. Run on release mode `flutter run -d chrome --release`
3. Click on increment FAB.

Removing `read()` on the StateNotifier class fixes it. Works fine on debug mode.

Flutter doctor
```
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0-3.4.pre at /home/sdk/flutter
    • Framework revision e6b34c2b5c (9 hours ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1
```

**Comment by mono0926** [comment]
Reported here: https://github.com/rrousselGit/provider/issues/406.
And the bug is tracked here: https://github.com/dart-lang/sdk/issues/41449.

**Comment by justinenerio** [comment]
Thanks! Will follow the bug tracker. Closed.
