### ISSUE TITLE
Test failures swallowed in addListener callback

### ISSUE THREAD

**Issue by frank06** [rrousselGit/state_notifier#20]
I am testing stuff inside of the `addListener` callback, but since errors are caught and "redirected" to `onError`, test failures are never exposed:

```dart
    notifier.addListener(
      expectAsync1((model) {
        if (i == 0) expect(model, matcher);
        if (i == 1) expect(model, matcher);
        i++;
      }, count: 2),
      fireImmediately: false,
    );
```

Any of those `expect`s failing, and the test will still pass.

I tried different ways of overriding the callback but none report back the failure:

```dart
    notifier.onError = (err, stack) {
      throw err;
      // print(err);
      // throw TestFailure(err.toString());
    };
```

So my first workaround is checking on the counter at the end of the test:

```dart
expect(i, equals(2));
```

Any better ideas or workarounds?

**Comment by rrousselGit** [comment]
Hum onError could default to Zone.current.handleUncaughtError

**Comment by frank06** [comment]
```dart
notifier.onError = Zone.current.handleUncaughtError;
```

does indeed work. Thank you Remi for the speedy response and the black magic!

**Comment by rrousselGit** [comment]
I'll make a pr that makes it the default

**Comment by rrousselGit** [comment]
What do you mean by pain?

**Comment by frank06** [comment]
There was an exception thrown inside a listener and there was no way to trace back to the line that caused it. Debugger jumped to the `state_notifier` package line with `throw Error()`, arguments `error` and `stackTrace` are not helpful.

Using `0.5.0`

**Comment by frank06** [comment]
Why not throw the error directly?

```dart
try {
        listenerEntry.listener(value);
      } catch (error, stackTrace) {
        if (onError != null) {
          onError(error, stackTrace);
        } else {
          throw error;
        }
      }
```

**Comment by rrousselGit** [comment]
It notifies all listeners first.
Otherwise some listeners could be left out
