### ISSUE TITLE
does it support consumer/selector ?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/state_notifier#21]
does it support consumer/selector ?

**Comment by rrousselGit** [comment]
Yes it does

It supports all provider features.

**Comment by tbm98** [comment]
can you give me some example about use selector/consumer with state_notifier?

**Comment by rrousselGit** [comment]
Here's context.select

https://github.com/rrousselGit/state_notifier/blob/eceb2d9ce0091b53a5d4c23336daf5fd35a6673d/packages/flutter_state_notifier/example/lib/main.dart#L83

You should be able to infer on how to use Consumer/Select from that

**Comment by tbm98** [comment]
Thanks

Vào 17:46 Th 7, 13 thg 6 2020 Remi Rousselet <notifications@github.com> đã
viết:
