### ISSUE TITLE
…Notifier or …Controller?

### ISSUE THREAD

**Issue by reedom** [rrousselGit/state_notifier#39]
**Describe what scenario you think is uncovered by the existing examples/articles**

`…Notifier` is found in the example code 
https://github.com/rrousselGit/state_notifier/blob/master/example/lib/my_state_notifier.dart#L19

and `…Controller` is in the comment.
https://github.com/rrousselGit/state_notifier/blame/57e64d0a8dc029ad457217cc0f210944083dc212/packages/flutter_state_notifier/lib/flutter_state_notifier.dart#L121-L123

It'd be nice if they've followed the same convention.

**Describe why existing examples/articles do not cover this case**

It could be a big help to end arguments upon those in teams. 😅

**Comment by rrousselGit** [comment]
Both are technically correct

I'd say prefer "notifier" because of the class/package name. But "controller" is absolutely fine too.
Notifiers _are_ contollers.
