### ISSUE TITLE
Add null safety to this package

### ISSUE THREAD

**Issue by bizz84** [rrousselGit/state_notifier#43]
**Is your feature request related to a problem? Please describe.**

Apps that use Provider and StateNotifier need a corresponding null-safety version of this package.

**Comment by rrousselGit** [comment]
It already exists: 0.7.0-nullsafety.0

**Comment by rrousselGit** [comment]
Oh wait, maybe you're talking about `flutter_state_notifier` instead?

**Comment by bizz84** [comment]
Yes. we need null-safety for `flutter_state_notifier` as well.

**Comment by Sameerkash** [comment]
@rrousselGit  is there's no WIP on this, I'd like to help!
