### ISSUE TITLE
Use of the Future in the StateNotifier

### ISSUE THREAD

**Issue by kmartins** [rrousselGit/state_notifier#47]
When I use the future in `StateNotifier` and the `state` is changed with the response this `future`, but the response arrives after the `dispose` of the `Statenotifier`.

Do I have to verify `mounted` before changed the `state` always?

Because I'm getting:
```Tried to use $runtimeType after `dispose` was called. Consider checking `mounted`.```

**Comment by rrousselGit** [comment]
You should preferably override `dispose` to cancel pending futures.

**Comment by kmartins** [comment]
Right, but why do not replace `assert (_debugIsMounted (), ‘’);` for the `if (mounted)` in the set state?
