### ISSUE TITLE
Overhead in dispatching notifications with StateNotifier vs ValueNotifier

### ISSUE THREAD

**Issue by Mabsten** [rrousselGit/state_notifier#49]
The documentation of `ChangeNotifier`, of which 'ValueNotifier` is basically a simple variant (albeit with different practical uses), says that 

> It is O(1) for adding listeners and **O(N) for** removing listeners and **dispatching notifications** (where N is the number of listeners)"

The documentation of `StateNotifier` however asserts that   
> listeners cannot add extra listeners.
> This makes notifying listeners O(N) versus O(N²) for ValueNotifier

TL;DR:
Notifying listeners with ValueNotifier is **O(N²)** (as stated by state_notifier Readme) or **O(N)** (as stated by ChangeNotifier doc) ?

In the second case, the two classes are equivalent in terms of notifying listeners overhead (obviously not with regard to removal listeners).

**Comment by Mabsten** [comment]
I got it. Thanks for the reply

**Comment by rrousselGit** [comment]
I have removed the mention, so I will close this.
