### ISSUE TITLE
Analyzer goes mental after upgrade to Flutter 2.5 and Dart 2.14

### ISSUE THREAD

**Issue by arnoutvandervorst** [rrousselGit/state_notifier#53]
After the upgrade to Flutter 2.5 and Dart 2.14, I get analysis errors on every file I open and errors when running the build_runner. The analysis server instrumentation log reveals this error on every single file:

1631182843704:Ex:Analysis failed:: /Users/arnoutvandervorst/Projects/newme_app/test/widget_test.dart context:: exception_20210909_122043_559
Invalid argument(s):: Unexpectedly not indexed:: Notifier extends StateNotifier<State>
#0      _LocalElementIndexer.[] (package::analyzer/src/summary2/bundle_writer.dart::944::10)

Can it be related to this package and the upgrade to Dart 2.14?

**Comment by rrousselGit** [comment]
It's highly unlikely to be state_notifier's fault

Try `flutter clean`, upgrading your dependencies and restarting your IDE

**Comment by arnoutvandervorst** [comment]
https://github.com/dart-lang/sdk/issues/47171

**Comment by rrousselGit** [comment]
Looks like this is a Dart bug. So I'll close this since there's nothing I can do

Thanks for the report.
