### ISSUE TITLE
Request updateShouldNotify

### ISSUE THREAD

**Issue by nogaten** [rrousselGit/state_notifier#54]
**Is your feature request related to a problem? Please describe.**
In the new version of StateNotifier, there is a fix that does not notify listeners if it is identical when updating state.
Sometimes I want to notify listeners even if the objects is identical.
I want you to be able to choose whether to notify listeners.

**Describe the solution you'd like**
I would like a method like the one below and I want it to be able to be overridden.
```dart
bool updateShouldNotify(T previous, T current) {
  return !identical(previous, current);
}
```

**Comment by ebelevics** [comment]
It seems I'm not the only one facing this issue. I have provided suggestion to overcome this issue in pull request https://github.com/rrousselGit/state_notifier/issues/54.
