### ISSUE TITLE
Stream returned `stream` getter should notify with the current state immediately on listen

### ISSUE THREAD

**Issue by maBarabas** [rrousselGit/state_notifier#78]
**Is your feature request related to a problem? Please describe.**

StreamNotifier.steam returns a broadcast stream that is idle until the state is set. It should instead notify the current state immediately.

**Describe the solution you'd like**

The `stream` getter should return a [ValueStream](https://pub.dev/documentation/rxdart/latest/rx/ValueStream-class.html) constructed using [BehaviorSubject.seeded](https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject/BehaviorSubject.seeded.html) or something similar. This variant of the stream always notifies with the last known value on listen, which is consistent with how the StateNotifier.addListener works.

**Describe alternatives you've considered**

This extension is consistent with `addListener`:

```
extension _StateEx<T> on StateNotifier<T> {
  ValueStream<T> get valueStream {
    // ignore: invalid_use_of_protected_member
    return stream.shareValueSeeded(state);
  }
}
```

**Comment by rrousselGit** [comment]
Hello!

This would be breaking and likely require an extra dependency or a lot of work. I have no plan to do such a thing.
So while I appreciate the request, I'll close this as it won't be worked on :)
